/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 celcius.gltf --transform 
Files: celcius.gltf [9.49MB] > celcius-transformed.glb [210.96KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/celcius-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bodi.geometry} material={materials.Default_Material} material-color={"#000000"} />
      <mesh geometry={nodes.ban.geometry} material={nodes.ban.material} />
    </group>
  )
}

useGLTF.preload('/celcius-transformed.glb')
