/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 micro.gltf 
*/

import React, { useRef } from 'react'
import {AccumulativeShadows, RandomizedLight, useGLTF,Text3D,Text } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({color,numero,linea,girar,avanzar,retroceder,props}) {
  const { nodes, materials } = useGLTF('/Micro.gltf')

  const rueda = useRef();
  const rueda2 = useRef();
  const rueda3 = useRef();
  const rueda4 = useRef();

  const bus = useRef();

  useFrame((_state,delta) => {
    if(avanzar){
      rueda.current.rotation.x += delta * 1;
      rueda2.current.rotation.x += delta * 1;
      rueda3.current.rotation.x += delta * 1;
      rueda4.current.rotation.x += delta * 1;

      bus.current.position.z += delta * 0.5;  
    }else{
      if(retroceder === true){
        rueda.current.rotation.x += delta * -1;
        rueda2.current.rotation.x += delta * -1;
        rueda3.current.rotation.x += delta * -1;
        rueda4.current.rotation.x += delta * -1;
  
        bus.current.position.z += delta * -0.5;  
      }
    }
    
  })


  return (
    <group castShadow receiveShadow  {...props} dispose={null} ref={bus}>
      <Text3D position={[-0.76,1.46, 4.05]}  font="Inter_ExtraBold.json" size={0.15} height={0.04} type='font'  >
        {numero}
        <meshStandardMaterial color={linea} toneMapped={true} />
      </Text3D>
      <Text position={[-1.05,0.8,0.-0.1]} rotation={[0,-Math.PI/2,0]}  font="Inter_ExtraBold.json" fontSize={0.5}>
        {numero}
        <meshStandardMaterial color={linea} toneMapped={true} />
      </Text>
      <Text position={[1.05,0.8,0.-0.1]} rotation={[0,Math.PI/2,0]}  font="Inter_ExtraBold.json" fontSize={0.5}>
        {numero}
        <meshStandardMaterial color={linea} toneMapped={true} />
      </Text>
      <AccumulativeShadows>
        <RandomizedLight position={[2, 5, 5]} />
      </AccumulativeShadows> 
      <mesh castShadow geometry={nodes['base2(int)'].geometry} material={materials.Interior} position={[0.22, 1.67, 1.605]} material-color={"#2A253B"} />
      <group position={[0.097, 1.515, 0.443]} >
        <mesh castShadow  geometry={nodes.bus_1.geometry} material={materials['Material.001']} material-color={color} />
        <mesh castShadow  geometry={nodes.bus_2.geometry} material={materials.Exterior} material-color={"gray"} />
      </group>
      <mesh geometry={nodes.glass.geometry} material={materials.glass}/>

      <mesh geometry={nodes.w_F_1.geometry} material={materials.Rueda} position={[-0.887, 0.465, 2.441]}  material-color={"#353131"} ref={rueda}  />
      <mesh geometry={nodes.w_F_0.geometry} material={materials.Rueda} position={[0.887, 0.465, 2.441]} rotation={[-0.006, 0, 0]} ref={rueda2} />
      <mesh geometry={nodes.w_R_1.geometry} material={materials.Rueda} position={[-0.756, 0.465, -2.207]} ref={rueda3} />
      <mesh geometry={nodes.w_R_0.geometry} material={materials.Rueda} position={[0.756, 0.465, -2.207]}  ref={rueda4} />
      <mesh geometry={nodes.steering_w.geometry} material={materials.volante} position={[0.609, 1.528, 3.776]} rotation={[0, girar * 0.1, 0]} />
      <mesh geometry={nodes.Cubo.geometry} material={materials.Cuadro} position={[-0.604, 1.534, 4.029]} rotation={[Math.PI, 0, 0]} scale={[0.588, 0.533, 0.015]}  material-color={"gray"} />
      {/* <mesh geometry={nodes['21'].geometry} material={materials['Material.001']} position={[-0.755, 1.453, 4.08]} rotation={[1.575, 0, 0]} scale={[0.316, 1.043, 0.294]} /> */}
      <mesh geometry={nodes.linea.geometry} material={materials.lineas} position={[-1.053, 1.399, -0.422]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.053, -1, -3.195]} material-color={linea} />
      <mesh geometry={nodes.linea2.geometry} material={materials.lineas} position={[1.047, 1.399, -0.422]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.079, -1, -3.195]} />
      <mesh geometry={nodes.linea3.geometry} material={materials.lineas} position={[-0.007, 1.111, 4.24]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[-0.02, -1, -0.539]} />
      <mesh geometry={nodes.linea_4.geometry} material={materials.lineas} position={[-1.053, 1.548, -3.005]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.036, -1, -1.128]} />
      <mesh geometry={nodes.linea_5.geometry} material={materials.lineas} position={[-1.053, 1.551, -0.599]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.036, -1, -1.128]} />
      <mesh geometry={nodes.linea_6.geometry} material={materials.lineas} position={[-1.053, 1.03, -3.592]} rotation={[-3.138, 0, -Math.PI / 2]} scale={[-0.036, -1, -0.699]} />
    </group>
  )
}

useGLTF.preload('/Micro.gltf')
