/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 microMod.gltf 
*/

import React, { useRef } from 'react'
import {AccumulativeShadows, RandomizedLight, useGLTF,Text3D,Text } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({color,numero,linea,linea2,girar,abrir, cerrar,avanzar,retroceder,props}) {
  const { nodes, materials } = useGLTF('/microMod.gltf')

  const rueda = useRef();
  const rueda2 = useRef();
  const rueda3 = useRef();
  const rueda4 = useRef();

  const aro = useRef();
  const aro2 = useRef();
  const aro3 = useRef();
  const aro4 = useRef();

  const puertaD = useRef();
  const puertaI = useRef();


  const bus = useRef();

  useFrame((_state,delta) => {
    if(avanzar){
      rueda.current.rotation.x += delta * -2;
      rueda2.current.rotation.x += delta * -2;
      rueda3.current.rotation.x += delta * -2;
      rueda4.current.rotation.x += delta * -2;

      aro.current.rotation.x += delta * -2;
      aro2.current.rotation.x += delta * -2;
      aro3.current.rotation.x += delta * -2;
      aro4.current.rotation.x += delta * -2;

      bus.current.position.z += delta * -1;  
    }else if(retroceder === true){
      rueda.current.rotation.x += delta * 2;
      rueda2.current.rotation.x += delta * 2;
      rueda3.current.rotation.x += delta * 2;
      rueda4.current.rotation.x += delta * 2;

      aro.current.rotation.x += delta * 2;
      aro2.current.rotation.x += delta * 2;
      aro3.current.rotation.x += delta * 2;
      aro4.current.rotation.x += delta * 2;

      bus.current.position.z += delta * 1;
    }
    if(abrir){
      if(puertaD.current.rotation.z<(Math.PI/2.2)){
        puertaI.current.rotation.z -= delta * 1;
        puertaI.current.position.z -= delta * 1.45;   
        puertaD.current.rotation.z += delta * 1;
      }
    }
    else if(cerrar){
      if(puertaI.current.rotation.z<0){
        puertaI.current.rotation.z += delta * 1;
        puertaI.current.position.z += delta * 1.45;
        puertaD.current.rotation.z -= delta * 1;
      }
    }

    
  })

  return (
    <group ref={bus} {...props} dispose={null}>
    <Text3D position={[1.2+(numero+'').length/2*0.29, 4.3, -9.0]} scale={[0.4, 0.5, 0.4]} rotation={[0,Math.PI,0]}  font="Inter_ExtraBold.json">
      {numero}
      <meshStandardMaterial color={linea2} toneMapped={true} />
    </Text3D>
      <Text position={[0.15,3.3,-9.78]} rotation={[0,-Math.PI,0]}  font="Inter_ExtraBold.json" fontSize={0.8} type='font'  >
        {numero}
        <meshStandardMaterial color={linea} toneMapped={true} />
      </Text>
      <Text position={[-3,2.9,-4.2]} rotation={[0,-Math.PI/2,0]} font="Inter_ExtraBold.json" fontSize={1}>
        {numero}
        <meshStandardMaterial color={linea2} toneMapped={false} />
      </Text>
      <Text position={[3.15,3,-6]} rotation={[0,Math.PI/2,0]}  font="Inter_ExtraBold.json" fontSize={0.5}>
        {numero}
        <meshStandardMaterial color={linea2} toneMapped={true} />
      </Text>
      <mesh geometry={nodes.Chasis.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cortinas.geometry} material={materials['Material.011']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Chasis_piso.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mecanismo_del_cinturon.geometry} material={materials.Tapiz} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cinturon_de_seguridad.geometry} material={materials.accesorios} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cinturon_Hebilla.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Luces_de_posicion.geometry} material={materials['Material.006']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Luces_interiores.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Aro_de_repuesto.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Hacientos.geometry} material={materials.Interior} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Chasis_piso_interior.geometry} material={materials.Piso} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Carroceria_interior.geometry} material={materials.Tapiz} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Puntos_de_la_cabina.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Visera_parasol.geometry} material={materials.Tapiz} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ParaPuertas.geometry} material={materials.Piso} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_17nr004.geometry} material={materials.Tapiz} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_17nr005.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_17nr006.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_17nr007.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Guardabarros.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Marco_delantero.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      {/* <mesh geometry={nodes.Vidrio_delantero.geometry} material={materials.Glass} position={[0.06, -0.184, 0.14]} rotation={[Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.mesh_0_18nr003.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tubo_de_escape.geometry} material={materials['Material.007']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0_20nr.geometry} material={materials.exterior} material-color={color} />
        <mesh geometry={nodes.mesh_0_20nr_1.geometry} material={materials.exterior} material-color={color} />
      </group>
      {/* <mesh geometry={nodes.Vidrio_trasero.geometry} material={materials.Glass} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} /> */}
      {/* <mesh geometry={nodes.mesh_0_20nr002.geometry} material={materials.GLASS} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Puerta_vidrioD.geometry} material={materials.Glass} position={[2.768, 4.646, -3.547]} rotation={[Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.mesh_0_20nr005.geometry} material={materials['Material.003']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr006.geometry} material={materials['Material.003']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Defensa_delantera.geometry} material={materials.exterior} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr008.geometry} material={materials.focos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr009.geometry} material={materials['exterior.001']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr010.geometry} material={materials.exteriorbajo} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr011.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr012.geometry} material={materials.exterior} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rejilla_delantera.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr014.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ventana_copiloto.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ventana_izquierda.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr017.geometry} material={materials.exterior}  material-color={color} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Manija_trasera.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Marco_trasero.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LimpiaParabrisa.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      {/* <mesh geometry={nodes.mesh_0_20nr021_mesh_0_20nr022.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr022_mesh_0_20nr023.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.Agaramanos.geometry} material={materials.Piso} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr024_mesh_0_20nr025.geometry} material={materials.accesorios} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ventanas_derechas.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr026_mesh_0_20nr027.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0_20nr027_mesh_0_20nr028.geometry} material={materials.exterior} />
        <mesh geometry={nodes.mesh_0_20nr027_mesh_0_20nr028_1.geometry} material={materials.exterior} />
      </group>
      <mesh geometry={nodes.Manija_de_la_puerta.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr029.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr030.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr031.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh_0_20nr032.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Ventana_Piloto.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      {/* <mesh geometry={nodes.Puerta_interior.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} /> */}
      {/* <mesh geometry={nodes.mesh_0_20nr051.geometry} material={materials.Glass} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.AroD1.geometry} material={materials['Material.007']} position={[2.445, 1.075, -7.094]} rotation={[Math.PI / 2, 0, 0]}  ref={aro4}/>
      <mesh geometry={nodes.Caja_de_cambios.geometry} material={materials.accesorios} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Logotipo_Marca.geometry} material={materials.marca} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Luces_de_direccion.geometry} material={materials['Material.006']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Luces_traseras.geometry} material={materials['Material.012']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Luces_delanteras.geometry} material={materials.focos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Motor.geometry} material={materials['Material.001']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Volante.geometry} material={materials.volante} position={[-1.628, 4.215, -8.024]} rotation={[Math.PI / 2, 0, girar/20]} />
      <mesh geometry={nodes.Retrovisores.geometry} material={materials.espejos} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Retrovisor_central.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Retrovisor_derecho.geometry} material={materials.Llantas} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Retrovisor_izquierdo.geometry} material={materials['Material.007']} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tablero.geometry} material={materials.Tapiz} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      {/* <mesh geometry={nodes.Vidrios_pasajeros1.geometry} material={materials.Glass} position={[0, -0.159, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Vidrios_pasajeros2.geometry} material={materials.Glass} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Vidrios_pasajeros3.geometry} material={materials.Glass} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Vidrios_central.geometry} material={materials.Glass} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Vidrios_piloto_copiloto.geometry} material={materials.Glass} position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.Plane005.geometry} material={materials.exterior} material-color={color}  position={[0, -0.159, 0.142]} rotation={[Math.PI / 2, 0, 0]}  />
      <mesh geometry={nodes.linea.geometry} material={materials.lineas} position={[3.123, 3.114, 4.421]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.089, -1, -6.148]}  material-color={linea}/>
      <mesh geometry={nodes.linea001.geometry} material={materials.lineas1} position={[3.123, 3.404, 4.421]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.089, -1, -6.148]} material-color={linea} />
      <mesh geometry={nodes.linea002.geometry} material={materials.lineas1} position={[3.123, 2.727, 8.842]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.089, -1, -1.225]} />
      <mesh geometry={nodes.linea003.geometry} material={materials.lineas1} position={[3.123, 2.418, 8.842]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.089, -1, -1.225]} />
      <mesh geometry={nodes.linea004.geometry} material={materials.lineas1} position={[3.123, 2.78, 1.784]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.089, -1, -1.225]} />
      <mesh geometry={nodes.linea005.geometry} material={materials.lineas2} position={[3.167, 1.882, 8.842]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.164, -1, -1.619]} material-color={linea2} />
      <mesh geometry={nodes.linea006.geometry} material={materials.lineas2} position={[3.167, 1.882, 1.571]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.164, -1, -1.619]} />
      <mesh geometry={nodes.Cubo.geometry} material={materials.Cuadro} position={[1.123, 4.591, -8.901]} rotation={[Math.PI, 0, 0]} scale={[1.616, 1.224, 0.015]} />
      <mesh geometry={nodes.linea007.geometry} material={materials['lineas2.001']} position={[-2.943, 1.802, 1.13]} rotation={[-Math.PI, 0, -1.545]} scale={[-0.185, -1, -1.619]} material-color={linea2} />
      <mesh geometry={nodes.linea008.geometry} material={materials.lineas2} position={[-2.943, 1.802, 8.401]} rotation={[-Math.PI, 0, -1.545]} scale={[-0.185, -1, -1.619]} />
      <mesh geometry={nodes.linea009.geometry} material={materials['lineas1.001']} position={[-2.964, 2.701, 1.343]} rotation={[-Math.PI, 0, -1.545]} scale={[-0.089, -1, -1.225]} />
      <mesh geometry={nodes.linea010.geometry} material={materials.lineas1} position={[-2.973, 2.339, 8.401]} rotation={[-Math.PI, 0, -1.545]} scale={[-0.089, -1, -1.225]} material-color={linea} />
      <mesh geometry={nodes.linea011.geometry} material={materials['lineas1.001']} position={[-2.965, 2.648, 8.401]} rotation={[-Math.PI, 0, -1.545]} scale={[-0.089, -1, -1.225]} material-color={linea} />
      <mesh geometry={nodes.linea012.geometry} material={materials['lineas1.001']} position={[-2.948, 3.325, 3.98]} rotation={[-Math.PI, 0, -1.545]} scale={[-0.089, -1, -6.148]} />
      <mesh geometry={nodes.linea013.geometry} material={materials['lineas.001']} position={[-2.955, 3.035, 3.98]} rotation={[-Math.PI, 0, -1.545]} scale={[-0.089, -1, -6.148]} material-color={linea} />
      <mesh geometry={nodes.LlantaD2.geometry} material={materials['Llantas.001']} position={[2.331, 1.082, 5.165]} rotation={[Math.PI / 2, 0, 0]} ref={rueda} />
      <mesh geometry={nodes.LlantaD1.geometry} material={materials['Llantas.003']} position={[2.326, 1.079, -7.088]} rotation={[Math.PI / 2, 0, 0]} ref={rueda2} />
      <mesh geometry={nodes.LlantaI1.geometry} material={materials['Llantas.005']} position={[-2.135, 1.076, 5.183]} rotation={[Math.PI / 2, 0, 0]} ref={rueda3} />
      <mesh geometry={nodes.LlantaI2.geometry} material={materials['Llantas.006']} position={[-2.126, 1.084, -7.076]} rotation={[Math.PI / 2, 0, 0]} ref={rueda4} />
      <mesh geometry={nodes.AroI1.geometry} material={materials['Material.002']} position={[-2.258, 1.081, -7.078]} rotation={[Math.PI / 2, 0, 0]} ref={aro} />
      <mesh geometry={nodes.AroD2.geometry} material={materials['Material.004']} position={[2.355, 1.086, 5.175]} rotation={[Math.PI / 2, 0, 0]} ref={aro2} />
      <mesh geometry={nodes.AroI2.geometry} material={materials['Material.005']} position={[-2.087, 1.082, 5.181]} rotation={[Math.PI / 2, 0, 0]} ref={aro3}/>
      <group ref={puertaD} position={[2.811, 3.701, -5.417]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0_20nr004.geometry} material={materials.exterior}  material-color={color} />
        <mesh geometry={nodes.mesh_0_20nr004_1.geometry} material={materials.exterior} />
      </group>
      <group ref={puertaI} position={[2.795, 3.674, -2.898]} rotation={[Math.PI /2, 0, 0]}>
        <mesh geometry={nodes.mesh_0_20nr269.geometry} material={materials.exterior}  material-color={color} />
        <mesh geometry={nodes.mesh_0_20nr269_1.geometry} material={materials.exterior} />
      </group>

      {/* <mesh geometry={nodes.Puerta_vidrioI.geometry} material={materials['Glass.001']} position={[2.783, 4.634, -4.833]} rotation={[Math.PI / 2, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('/microMod.gltf')
