/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 micromitsu.gltf --transform 
Files: micromitsu.gltf [6.1MB] > micromitsu-transformed.glb [1.14MB] (81%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/micromitsu-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chasis.geometry} material={materials.PaletteMaterial001} position={[0, -1.207, 3.082]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mecanismo_del_cinturon.geometry} material={materials.PaletteMaterial002} position={[0, -1.207, 3.082]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Chasis_piso_interior.geometry} material={materials.PaletteMaterial003} position={[0, -1.207, 3.082]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Vidrio_delantero.geometry} material={materials.PaletteMaterial004} position={[0.06, -1.232, 3.08]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cubo.geometry} material={materials.PaletteMaterial002} position={[1.123, 3.543, -5.961]} rotation={[Math.PI, 0, 0]} scale={[1.616, 1.224, 0.015]} />
      <instancedMesh args={[nodes.Plano.geometry, materials.PaletteMaterial002, 12]} instanceMatrix={nodes.Plano.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/micromitsu-transformed.glb')
